Repository this-place/this.place, pull requests merged in 2018-03, with the labels that each got.

#36 feat: update character prefab to use new model
  Assets/Models.meta
  Assets/Models/Character.meta
  Assets/Models/Character/arm.bmp
  Assets/Models/Character/arm.bmp.meta
  Assets/Models/Character/body2.bmp
  Assets/Models/Character/body2.bmp.meta
  Assets/Models/Character/hair.bmp
  Assets/Models/Character/hair.bmp.meta
  Assets/Models/Character/hat.bmp
  Assets/Models/Character/hat.bmp.meta
  Assets/Models/Character/head.bmp
  Assets/Models/Character/head.bmp.meta
  Assets/Models/Character/leg.bmp
  Assets/Models/Character/leg.bmp.meta
  Assets/Models/Character/mainchara.fbx
  Assets/Models/Character/mainchara.fbx.meta
  Assets/Prefabs/Character.prefab
Labels: feature

#66 fix: highlight disappears when mouse leaves a block
  Assets/Scripts/PlayerMouse.cs
Labels: fix

#60 feat: blocks turn invisible
  Assets/Materials/GrassAtlas.mat
  Assets/Materials/StoneTiled.mat
  Assets/Materials/grass.mat
  Assets/Materials/sand.mat
  Assets/Materials/stone.mat
  Assets/ScriptableObjects/Fadeout.asset
  Assets/ScriptableObjects/Fadeout.asset.meta
  Assets/ScriptableObjects/Plugin Scripts/BlockPlugin.cs
  Assets/ScriptableObjects/Plugin Scripts/FadeoutPlugin.cs
  Assets/ScriptableObjects/Plugin Scripts/FadeoutPlugin.cs.meta
  Assets/Scripts/CameraController.cs
Labels: feature

#61 feat: tutorial stage
  Assets/Scenes/Stages.meta
  Assets/Scenes/Stages/Tutorial.unity
  Assets/Scenes/Stages/Tutorial.unity.meta
  Assets/Scenes/gravel.unity
  Assets/Scripts/PlayerController.cs
Labels: feature

#72 chore: update texture atlas
  Assets/Materials/SandAtlas.mat
  Assets/Materials/SandAtlas.mat.meta
  Assets/Materials/Textures/SandAtlas.png
  Assets/Materials/Textures/SandAtlas.png.meta
  Assets/Prefabs/SandBlock.prefab
  Assets/Prefabs/StoneBlock.prefab
  Assets/Scenes/lighting.unity
Labels: chore

#73 feat: fragile particle system
  Assets/Prefabs/FragileEmitter.prefab
  Assets/Prefabs/FragileEmitter.prefab.meta
  Assets/Scenes/gravel.unity
  Assets/ScriptableObjects/Fragile.asset
  Assets/ScriptableObjects/Plugin Scripts/FragilePlugin.cs
  Assets/ScriptableObjects/Plugin Scripts/FragilePlugin.cs.meta
Labels: feature

#76 fix: incorrect uv mapping
  Assets/Scripts/UVMap.cs
Labels: fix

#86 feat: disintegrate block
  Assets/Materials/disintegrate.mat
  Assets/Materials/disintegrate.mat.meta
  Assets/Prefabs/DisintegrateBlock.prefab
  Assets/Prefabs/DisintegrateBlock.prefab.meta
  Assets/Scenes/sand.unity
  Assets/ScriptableObjects/Disintegrate.asset
  Assets/ScriptableObjects/Disintegrate.asset.meta
  Assets/ScriptableObjects/Plugin Scripts/DisintegratePlugin.cs
  Assets/ScriptableObjects/Plugin Scripts/DisintegratePlugin.cs.meta
  Assets/ScriptableObjects/Plugin Scripts/IDisplaceable.cs
  Assets/ScriptableObjects/Plugin Scripts/IDisplaceable.cs.meta
  Assets/ScriptableObjects/Plugin Scripts/MoveablePlugin.cs
  Assets/Scripts/BlockBehaviour.cs
  Assets/Scripts/BlockFaceBehaviour.cs
  Assets/Scripts/PlayerMouse.cs
Labels: feature

#88 feat: improve player feeling
  Assets/Scripts/CameraController.cs
  Assets/Scripts/PlayerController.cs
  ProjectSettings/InputManager.asset
Labels: feature

#85 feat: bouncing block
  Assets/Animations.meta
  Assets/Animations/Blink.anim
  Assets/Animations/Blink.anim.meta
  Assets/Animations/Bounce.anim
  Assets/Animations/Bounce.anim.meta
  Assets/Animations/Cube.controller
  Assets/Animations/Cube.controller.meta
  Assets/Animations/Eyes.controller
  Assets/Animations/Eyes.controller.meta
  Assets/Bounce.anim
  Assets/Bounce.anim.meta
  Assets/Materials/Gradient.mat
  Assets/Materials/Gradient.mat.meta
  Assets/Materials/Shaders.meta
  Assets/Materials/Shaders/GradientShader.shader
  Assets/Materials/Shaders/GradientShader.shader.meta
  Assets/Prefabs/MonsterBlock.prefab
  Assets/Prefabs/MonsterBlock.prefab.meta
  Assets/Scenes/lighting.unity
  Assets/Sprites.meta
  Assets/Sprites/EyesSprite.png
  Assets/Sprites/EyesSprite.png.meta
Labels: feature

#95 fix: player does not tilt when colliding with wall
  Assets/Scripts/PlayerController.cs
Labels: fix

#96 feat: r resets current level
  Assets/Scenes/Stages/Tutorial.meta
  Assets/Scenes/Stages/Tutorial.unity
  Assets/Scenes/Stages/Tutorial/LightingData.asset
  Assets/Scenes/Stages/Tutorial/LightingData.asset.meta
  Assets/Scenes/Stages/Tutorial/ReflectionProbe-0.exr
  Assets/Scenes/Stages/Tutorial/ReflectionProbe-0.exr.meta
  Assets/Scripts/PlayerController.cs
  ProjectSettings/InputManager.asset
Labels: feature

#97 fix: missing logic for displaceable interface method in disintegrate
  Assets/ScriptableObjects/Plugin Scripts/DisintegratePlugin.cs
Labels: fix

#103 fix: player will not interact with nulls
  Assets/Scripts/PlayerMouse.cs
Labels: fix

#84 fix: fragile blocks no longer destroys player
  Assets/Scripts/BlockBehaviour.cs
  Assets/Scripts/PlayerAnimatorController.cs
Labels: fix

#99 feat: stage 1
  Assets/Models/Environment/Manmade.meta
  Assets/Models/Environment/Manmade/Bridges.meta
  Assets/Models/Environment/Manmade/Bridges/bridge_end.mtl
  Assets/Models/Environment/Manmade/Bridges/bridge_end.mtl.meta
  Assets/Models/Environment/Manmade/Bridges/bridge_end.obj
  Assets/Models/Environment/Manmade/Bridges/bridge_end.obj.meta
  Assets/Models/Environment/Manmade/Bridges/bridge_end_edge.mtl
  Assets/Models/Environment/Manmade/Bridges/bridge_end_edge.mtl.meta
  Assets/Models/Environment/Manmade/Bridges/bridge_end_edge.obj
  Assets/Models/Environment/Manmade/Bridges/bridge_end_edge.obj.meta
  Assets/Models/Environment/Manmade/Bridges/bridge_mid.mtl
  Assets/Models/Environment/Manmade/Bridges/bridge_mid.mtl.meta
  Assets/Models/Environment/Manmade/Bridges/bridge_mid.obj
  Assets/Models/Environment/Manmade/Bridges/bridge_mid.obj.meta
  Assets/Models/Environment/Manmade/Bridges/bridge_mid_edge.mtl
  Assets/Models/Environment/Manmade/Bridges/bridge_mid_edge.mtl.meta
  Assets/Models/Environment/Manmade/Bridges/bridge_mid_edge.obj
  Assets/Models/Environment/Manmade/Bridges/bridge_mid_edge.obj.meta
  Assets/Models/Environment/Manmade/Bridges/bridge_post.mtl
  Assets/Models/Environment/Manmade/Bridges/bridge_post.mtl.meta
  Assets/Models/Environment/Manmade/Bridges/bridge_post.obj
  Assets/Models/Environment/Manmade/Bridges/bridge_post.obj.meta
  Assets/Prefabs/Environment/Manmade.meta
  Assets/Prefabs/Environment/Manmade/Bridges.meta
  Assets/Prefabs/Environment/Manmade/Bridges/wooden_bridge.prefab
  Assets/Prefabs/Environment/Manmade/Bridges/wooden_bridge.prefab.meta
  Assets/Prefabs/Environment/Trees/tree_oak3.prefab
  Assets/Prefabs/Environment/Trees/tree_oak3.prefab.meta
  Assets/Prefabs/GravelBlock.prefab
  Assets/Scenes/Stages/Stage 1.unity
  Assets/Scenes/Stages/Stage 1.unity.meta
  Assets/Scenes/Stages/Tutorial.unity
Labels: feature, feedback

#106 feat: signboard
  Assets/Materials/Signboard.mat
  Assets/Materials/Signboard.mat.meta
  Assets/Materials/ka1.ttf
  Assets/Materials/ka1.ttf.meta
  Assets/Models/Environment/Manmade/Sign_Wooden_Blank_01.fbx
  Assets/Models/Environment/Manmade/Sign_Wooden_Blank_01.fbx.meta
  Assets/Prefabs/Environment/Wooden Sign.prefab
  Assets/Prefabs/Environment/Wooden Sign.prefab.meta
  Assets/Scenes/lighting.unity
  Assets/Scripts/SignInfo.cs
  Assets/Scripts/SignInfo.cs.meta
Labels: feature

#101 feat: add disintegrate block material
  Assets/Animations/DisintegrateAnim.meta
  Assets/Animations/DisintegrateAnim/Idle.anim
  Assets/Animations/DisintegrateAnim/Idle.anim.meta
  Assets/Animations/DisintegrateAnim/Released.anim
  Assets/Animations/DisintegrateAnim/Released.anim.meta
  Assets/Animations/DisintegrateAnim/Triggered.anim
  Assets/Animations/DisintegrateAnim/Triggered.anim.meta
  Assets/Animations/DisintegrateBlock.controller
  Assets/Animations/DisintegrateBlock.controller.meta
  Assets/Materials/Textures/GlowMask.png
  Assets/Materials/Textures/GlowMask.png.meta
  Assets/Materials/disintegrate.mat
  Assets/Models/Environment/Manmade/Materials.meta
  Assets/Post-Processing Profile.asset
  Assets/Prefabs/DisintegrateBlock.prefab
  Assets/ScriptableObjects/Plugin Scripts/DisintegratePlugin.cs
  Assets/Scripts/UVMap.cs
Labels: feature

#105 feat: Enemy Monster
  Assets/Animations/Bounce.anim
  Assets/Animations/Cube.controller
  Assets/Models/Environment/Manmade/Materials/Color_C18.mat
  Assets/Models/Environment/Manmade/Materials/Color_C18.mat.meta
  Assets/Models/Environment/Manmade/Materials/FrontColor.mat
  Assets/Models/Environment/Manmade/Materials/FrontColor.mat.meta
  Assets/Prefabs/MonsterBlock.prefab
  Assets/Scripts/BlockBehaviour.cs
  Assets/Scripts/EnemyAI.cs
  Assets/Scripts/EnemyAI.cs.meta
  Assets/Scripts/EnemyController.cs
  Assets/Scripts/EnemyController.cs.meta
  Assets/Scripts/PlayerController.cs
Labels: feature
